---
title: Maak een variabele en stel een startwaarde in
hero_image: images/banner.png
description: Maak een variabele en stel een startwaarde in
version: 4
listed: false
copyedit: false
last_tested: "2021-05-11"
steps:
  - 
    title: Maak een variabele en stel een startwaarde in
