title: scratch3-create-set-variable
hero_image: images/banner.png
description: scratch3-create-set-variable description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-11"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
