title: Create a variable and set a start value
hero_image: images/banner.png
description: scratch3-create-set-variable description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-11"
steps:
  - title: Create a variable and set a start value
