---
title: Creu newidyn a gosod gwerth cychwynnol
hero_image: images/banner.png
description: Creu newidyn a gosod gwerth cychwynnol
version: 4
listed: false
copyedit: false
last_tested: "2021-05-11"
steps:
  - title: Creu newidyn a gosod gwerth cychwynnol
