---
title: Crie uma variável e defina um valor inicial
hero_image: images/banner.png
description: Crie uma variável e defina um valor inicial
version: 4
listed: false
copyedit: false
last_tested: "2021-05-11"
steps:
  - title: Crie uma variável e defina um valor inicial
