---
title: Crea una variable y establece un valor inicial
hero_image: images/banner.png
description: Crea una variable y establece un valor inicial
version: 4
listed: false
copyedit: false
last_tested: "2021-05-11"
steps:
  - 
    title: Crea una variable y establece un valor inicial
