---
title: Crear una variable y establecer un valor inicial
hero_image: images/banner.png
description: Crear una variable y establecer un valor inicial
version: 4
listed: false
copyedit: false
last_tested: "2021-05-11"
steps:
  - title: Crear una variable y establecer un valor inicial
