---
title: Utwórz zmienną i ustaw wartość początkową
hero_image: images/banner.png
description: Utwórz zmienną i ustaw wartość początkową
version: 4
listed: false
copyedit: false
last_tested: "2021-05-11"
steps:
  - title: Utwórz zmienną i ustaw wartość początkową
