---
title: Créer une variable et définir une valeur de départ
hero_image: images/banner.png
description: Créer une variable et définir une valeur de départ
version: 4
listed: false
copyedit: false
last_tested: "2021-05-11"
steps:
  - 
    title: Créer une variable et définir une valeur de départ
